
QuickQuestion  = [
["What was your worst injury?"],
["What is the best Olympic sport to watch?"],
["Where have you been that you really want to return to?"],
["What wild animal would you like to keep as a pet?"],
["Where is the coolest place you've been on vacation?"],
["What is your favorite article of clothing you own?"],
["What wild animal would you be terrified to face?"],
["What subject could you ace on Jeopardy?"],
["What is a place you've always wanted to visit?"],
["What is the best way to eat a potato?"],
["If you had to move to a new state, where would you move?"],
["What is the best smell?"],
["What is the last frivolous thing you spent money on?"],
["What is the best equipment to play on at a playground?"],
["What is your guilty pleasure food?"],
["What was the last movie or show you really got into?"],
["What store can you spend a lot of time just looking around?"],
["What is your favorite non-alcoholic drink?"],
["Describe the socks you are wearing right now."],
["What is hanging on your refrigerator door?"],
["How many Taylor Swift songs can you name?"],
["Fill in the blank: When I dance, I look like a ___."],
["What is your favorite healthy food?"],
["What streaming service do you use most?"],
["How far do you live from where you grew up?"],
["What do you think of possums?"],
["Do you prefer pets to have traditional pet names or human names?"],
["What's the best kind of pie?"],
["Which is better: bar soap or liquid soap?"],
["What do you usually eat for breakfast?"],
["Do you prefer to wear a watch, or check the time on your phone?"],
["Can you whistle? If so, are you a good whistler?"],
["Have you ever sprayed whipped cream directly into your mouth?"],
["On a scale of 1-10, how daring of a rollercoaster rider are you?"],
["When you go on vacation, are you an overplanner? Or do you go with the flow?"],
["Do you read the instructions, or just wing it?"],
["Do you talk back to your GPS when it tells you what to do?"],
["What is your typical sneezing pattern?"],
["Where is the nearest swimming pool to where you are right now?"],
["What is the first app you open on your phone each morning?"],
["What do you impulse buy at the grocery store, even if it's not on the list?"],
["You get a free shirt of any color. What color do you choose?"],
["It's a snowy day, and you're stuck at home alone. What sounds fun to do?"],
["What's your favorite number?"],
["What is your favorite food topping (on anything)?"],
["What is your phone's wallpaper right now?"],
["What is the farthest you've ever walked?"],
["You get two scoops of ice cream. What flavors do you choose?"],
["What is the perfect temperature outside?"],
["How low do you let your cell phone battery go before you charge it?"],
["Which is the better strategy: same lottery numbers every week or pick at random?"],
];


/*-------------------------------------*/
/*-------------------------------------*/
/*-------------------------------------*/


DiscQuestion = [
["What is a question you have that Google can't answer?"],
["What is an embarrassing situation from your past that you're willing to admit?"],
["What is something kind that a stranger has done for you?"],
["What is a small part of your life that you really enjoy?"],
["If you had to give a half hour talk right now, what could you talk about?"],
["What is something you hated as a kid, but love now?"],
["What is a country whose name you know, but have no idea where it is?"],
["What's a pet peeve you find particularly annoying?"],
["What's a quality in someone that makes you respect them instantly?"],
["What's a show or movie that you always stop to watch when it's on TV?"],
["What is a word that you say wrong on purpose because it's funny?"],
["What is something from your childhood that kids today won't understand?"],
["What is a word or saying local to the area where you live?"],
["When you hear <i>a guy walks into a bar</i> jokes, what kind of bar do you picture?"],
["Where is the most embarrassing public place you've fallen asleep?"],
["When you hear the words <i>school lunch</i>, what do you think of?"],
["What is a word you mispronounced for a long time?"],
["What is something in popular culture that you just don't get?"],
["What is something everyone should experience at least once?"],
["What is a recurring dream that you have?"],
["What would a perfect vacation day look like to you?"],
["You have to go on a TV game show. What show do you choose?"],
["What's something seemingly simple that blows your mind?"],
["If you could magically make one food healthy, what food would you choose?"],
["What's a good old-timey name you don't hear anymore?"],
["What is something that makes you think <i>How did nature make that</i>?"],
["What do you find inherently funny?"],
["How good are you at social media?"],
["What is a life skill they should teach you in school?"],
["What was your best Halloween costume?"],
["What word do you always spell wrong?"],
["What's a word that is fun to say?"],
["If you could own any fictional vehicle, which would you choose?"],
["What's a non-dessert food that you could eat like a dessert?"],
["You can choose any jigsaw puzzle. What is the picture you are piecing together?"],
["If you could open one small business specialty store, what would you sell?"],
["If you threw a message in a bottle into the sea, what would you write?"],
["If you were the leader of a popular band, how would you dress on stage?"],
["If you had a million dollars to donate to charity, which cause would you choose?"],
["What's a funny saying that only your family says?"],
["What is something you are weirdly snobbish about?"],
["What is the weirdest coincidence you've ever experienced?"],
["What is something you do now that your teenage self would laugh at?"],
["What is a weird tradition you or your family have?"],
["What would you do with some unexpected alone time?"],
["If you could change your birthday, what date would you choose?"],
["Going to DisneyWorld as an adult: Cool or kinda weird?"],
["If you could make money by putting commericals in your dreams, would you do it?"],
["Where do you wish you had grown up?"],
["What is a memorable meal you had (either good or bad)?"],
["What is something everyone seems to love, but you just don't get it?"],
["If you were typecast in movies, what character would you always play?"],
["What's a fad that, in retrospect, was kind of cool?"],
];



/*-------------------------------------*/
/*-------------------------------------*/
/*-------------------------------------*/




RidicQuestion = [
["If you were writing a political thriller, what would the president's name be?"],
["If our reality is just a simulation, what is the hypothesis being tested?"],
["How many pigeons could you carry for half a mile?"],
["If you were stuck in a Walmart for three days, how would you pass the time?"],
["What animal would you like to see on rollerskates?"],
["If you could run away and join the circus, what circus job would you want?"],
["If you had to eat a crayon, what color would you choose?"],
["What is a common word that sounds like it could be a swear word?"],
["Every time you greet someone, you make a sound effect. What sound do you choose?"],
["If a giraffe joined your band, what instrument would they play?"],
["You won a free session to fly an airplane banner. What will the message say?"],
["If you spoke with a different accent while on the phone, what accent would you choose?"],
["Your obituary says you died in the stupidest way ever. How did you die?"],
["If you could text former president Millard Fillmore, what would you say to him?"],
["What animal would make the most ridiculous sports team mascot?"],
["If potato chips were currency, what flavor would be the highest denomination?"],
["What do you wish you had a coupon for?"],
["If you could make one object out of legos then turn it real, what would you make?"],
["What would be the biggest challenge of living inside a giant mailbox?"],
["A cactus wants to know what it feels like to be hugged. What do you do?"],
["You can replace the ball in any sport with a fruit. What ball and fruit do you choose?"],
["On a scale of 1 to 10, how cool is your postal carrier?"],
["If there was one more verse in <i>The 12 Days of Christmas</i>, what would there be 13 of?"],
["What movie should be remade as a musical?"],
["You can put googly eyes on any one thing in the world without being caught. Where do they go?"],
["From now on, you can only speak in rhyme. How are you ordering dinner?"],
["You are dropped into a corn maze with 100 random people. How many can you beat out?"],
["You get $5,000 if you can beat any celebrity in a thumb wrestling match. Who do you choose?"],
["If there was a museum dedicated to you, what would the gift shop sell?"],
["You have to eat dinner at a gas station. What do you get?"],
["What is something you would describe as sophomoric?"],
["What would be the worst &quot],prize&quot], to come out when you break open a pi&ntildeata?"],
["If you went back in time 10 minutes, what would you do differently?"],
["If you could rename the state (or province) you live in, what would you name it?"],
["When you die, where would you like to come back and haunt?"],
["In a condiment fight, which condiment do you choose, and which do you give to your opponent?"],
["What animal would make the best stand-up comedian?"],
["If you had to choose any country as your middle name, what country would you choose?"],
["You have to convince a room full of people that you are an alien. How do you do it?"],
["You get a lifetime supply of any item you can buy at the dollar store. What do you choose?"],
["You are hired as a consultant to make elevators more fun. What are your suggestions?"],
["If you were made of of pasta, what kind of pasta would you look for in a mate?"],
["What would be the worst material to use for a raincoat?"],
["Your fortune teller has a drive through lane. What do you ask into the speaker?"],
["Where do you draw the line on wearing sweatpants in public?"],
["You have to buy dinner for your nemesis. Where are you taking them?"],
["Your travel agent offers a sale on a <i>mystery vacation</i>. Do you take it?"],
["If you learned how to hover 2 inches off the ground, how would it change your life?"],
["If you were in charge of the next census, what question would you make everyone answer?"],
["Do you think bowling pins feel pain, or are they excited to be knocked over?"],
["What are the pros and cons of dating a ghost?"],
["What is the upside of stubbing your toe?"],
["If your high school had Yelp reviews, how would you rate it?"],
];



/*-------------------------------------*/
/*-------------------------------------*/
/*-------------------------------------*/




WorkQuestion = [
["You get to add an extra holiday to the company calendar. Where do you put it?"],
["If you had to email the CEO an emoji right now, what would it be?"],
["Have you ever attended a conference call in your pajamas?"],
["How has AI impacted your job?"],
["What's the most mundane part of your job?"],
["What would you do if a co&#8209],worker inexplicably joined a large Zoom call in a Spiderman mask?"],
["If you work from home, what do you do with your saved commute time?"],
["Do you know your company's motto?"],
["How do you decompress after a particularly hard day at work?"],
["What coworker would you like to swap jobs with for a day?"],
["How many cups of coffee do you drink on an average day?"],
["How messy is your workspace?"],
["How many sticky notes do you have posted around your office?"],
["What energizes you at work?"],
["What's your best story while traveling for work?"],
["What's a skill that's not necessarily work related but has helped you at your job?"],
["What is a work skill that you admire in other people?"],
["How do you take a break while working from home?"],
["What is some office lingo that you find funny or annoying?"],
["What did you want to be when you grew up, and what do you do now?"],
["What would you do if you had a 3-month paid sabbatical?"],
["You fall asleep in a work meeting. What are you dreaming about?"],
["Your entire department is coming to your house for dinner. What are you cooking? (No takeout!)"],
["How often do you use LinkedIn?"],
["What coworker, past or present, have you learned the most from?"],
["What is something at work that immediately puts you in a bad mood?"],
["What is a non-monetary reward at work that makes you feel appreciated?"],
["You are in charge of your company's float in a large parade. What does it look like?"],
["What is your <i>I need to power through</i> snack?"],
["If you were an octopus, what would you do with your other six arms while at your computer?"],
["What is the best office supply to steal?"],
["If you had an unlimited budget, what would you buy for your home office?"],
["If your job was an adventure movie, what would the exciting action scene look like?"],
["During a typical work day, what percentage of your co&#8209],workers arrive before you?"],
["You have the world's most honest business card. What is your new job title?"],
["You're in charge of the office field trip! Where are you taking your office-mates?"],
["What's a work-related sound that you immediately recognize?"],
["What is a non-work related item on your desk?"],
["What is something work-related that you secretly enjoy?"],
["What is something you appreciate about your co-workers that isn't on any year-end review?"],
["What is a work task you do that gets you into flow state so you lose track of time?"],
["You are put in charge of your company's social media. How scared should the company be?"],
["Office birthday parties: cool or cringe?"],
];



/*-------------------------------------*/
/*-------------------------------------*/
/*-------------------------------------*/



PosQuestion = [
["What is a small thing in your life that you are grateful for?"],
["Who has really inspired you?"],
["What do you consider good self-care?"],
["What is your comfort food?"],
["How would your friends describe you?"],
["Describe your perfect cozy environment."],
["What is your best physical feature?"],
["What is something that makes you feel good about humanity?"],
["What is a random act of kindness that you have experienced?"],
["What is a good interaction you've had with a stranger that you'll never forget?"],
["Who makes you laugh?"],
["What is a quality that makes you like someone immediately?"],
["What is the most bad-ass thing you've ever done?"],
["What is the last thing you learned?"],
["What is a piece of art or media that always makes you feel good?"],
["What is something someone has done for you, and you never got to thank them?"],
["What is a company or organization that does good work?"],
["What makes you feel safe?"],
["What is something you are genuinely good at?"],
["What is a memorable micro-interaction you've had with a stranger?"],
["What do you contribute to the world?"],
["Why are you a catch?"],
["What is something you have done that you're proud of?"],
["What brings you joy?"],
["What is something tough that you survived?"],
["What is something your 12 year old self would think is cool about you today?"],
["Who is someone that thinks highly of you?"],
["What is something you are looking forward to?"],
["What is something about yourself that you are working on improving?"],
["What is somewhere that feels like home to you (that is not your home)?"],
["If you could see 10 years into the future, what would you be pleasantly surprised to see?"],
["What is the most beautiful view you have ever seen?"],
["What is a class or seminar you would like to teach to anyone who is interested?"],
["What is a personal achievement you've accomplished that others might not realize is a big deal?"],
["If you need a smile, what do you type into Google Image Search?"],
["What is an underrated activity you've added to your daily routine?"],
["What is something you enjoy sharing with other people?"],
["Describe your city or town like it's in a <i>Best Places to Live</i> article."],
["What is something about today that isn't terrible?"],
["What is a compliment you've received that has really stuck with you?"],
["What is something you like about where you are in life right now?"],
["If you got some really good news, who are the first people you want to tell?"],
];



/*-------------------------------------*/
/*-------------------------------------*/
/*-------------------------------------*/


KidQuestion = [
["What wild animal would you like to make friendly and keep as a pet?"],
["What is the grossest topping you could put on a pizza?"],
["What would your superhero outfit look like?"],
["If a turtle could talk, what would it say?"],
["If you had a helper robot, what would you have it do for you?"],
["You found a secret door in your house! What's on the other side?"],
["If you could design the perfect playground, what would it look like?"],
["What is the best snack food?"],
["You can choose any animal to be on your basketball team. What animal do you choose?"],
["If you were your teacher for the day, what would you do differently in class?"],
["If you could make one new school rule, what would it be?"],
["If you could design your own secret hideout, what would it look like?"],
["You wake up and find a dolphin in your bathtub! How did it get there?"],
["If you could go to any restaurant on your birthday, where would you go?"],
["What's the funniest word you can think of?"],
["If an alien landed in your backyard, what would it look like?"],
["If you had $100 to spend on presents, what would you buy and who would you give them to?"],
["If you could choose a vacation anywhere in the world, where would you go?"],
["What is the most fun activity to do outside?"],
["If it rained candy, what kind of candy would you want?"],
["Fill in the blank: Instead of math and reading, today in school we're going to talk about ___!"],
["What do you think lives in the secret forest?"],
["What TV show or movie would you like to live in?"],
["If you could do any jigsaw puzzle, what would it be a picture of?"],
["Your class has a secret guest visitor tomorrow! Who do you hope it is?"],
["If you carried a pet mouse around in your pocket, what would you name it?"],
["If you could have conversations with animals, what would you talk about?"],
["What do you think the moon smells like?"],
["Where would you go with a rocket powered skateboard?"],
["You can get a free shopping spree at any store. What store do you choose?"],
["What do penguins think about all day?"],
["If you had to name yourself after any famous person, what name would you choose?"],
];

