let dinglist = [
["Name 6 Mexican foods", 12],
["Name 6 words that start with G while strumming an air guitar", 11],
["Name 3 famous doctors and 3 types of peppers", 13],
["Name 5 things that are yellow", 12],
["Name 6 people jobs that wear a uniform", 13],
["Invent 3 new superhero catchphrases in a superhero voice", 15],
["Name 5 Shakespeare characters in an old English accent", 12],
["Name 5 ways to get $100", 13],
["Name 6 shoe brands", 15],
["Name 5 things that are black and white", 13],
["Name 6 accents while doing a different accent", 14],
["Name 5 famous books, but insert the word ham in the title", 11],
["Name 6 places that start with the word New", 13],
["Name 5 fruits that don't need to be peeled", 13],
["Name 5 pizza toppings that nobody wants", 12],
["Name 6 breakfast foods while pretending to flip a pancake", 11],
["Name 4 types of cheese and 4 types of pasta", 15],
["Name 5 things you find in a vending machine", 9],
["Name 6 vegetables while making a yuck face", 10],
["Name 5 farm animals while making their specific noises", 12],
["Name 5 US States in a cowboy accent", 10],
["Name 5 things with a clock while doing a robot voice", 12],
["Name 4 things you're afraid of in a tiny, squeaky voice", 9],
["Name 5 sports while pantomiming playing them", 11],
["Name 5 things you can find at a hardware store and 2 you can't", 12],
["Name 4 planets and 3 periodic table elements", 12],
["Name 6 things that are physically sticky", 12],
["Name 6 body parts that come in pairs", 10],
["Name 5 board games", 10],
["Name 7 words that rhyme with Light", 14],
["Name 5 instruments you blow into", 11],
["Name 6 hobbies that require a helmet", 11],
["Name 5 cartoon villains while laughing like one", 15],
["Name 5 people who were born before 1900", 12],
["Name 7 things that are smaller than a breadbox", 10],
["Name 5 items of clothing you'd wear in Antarctica", 12],
["Name 5 things you definitely won't see out the nearest window", 12],
["Name 5 excuses for being late", 15],
["Name 3 things that smell terrible and 4 things that smell great", 12],
["Name 6 words that contain the letter X", 12],
["Name 5 ways to cook an egg", 11],
["Name 3 things you should never do at a funeral", 12],
["Name 4 types of dinosaurs while stomping your feet", 11],
["Name 4 words that start and end with the same letter", 11],
["Name 4 sea animals and 4 land animals", 15],
["Name 5 things that are cold and name them while shivering", 12],
["Name 5 things to do to relax and name them while looking relaxed", 11],
["Name 5 things that make you laugh", 13],
["Name 5 things that are sticky", 13],
["Name 3 things that float and 3 things that sink", 14],
["Name 3 expensive things and 3 cheap things", 14],
["Name 4 things you can balance on your head", 9],
["Name 6 things under you can buy with a 10 dollar bill", 12],
["Name 5 things you see at a beach", 11],
["Name 3 things that are soft and 3 things that are hard", 12],
["Name 3 winter Olympic sports and 3 summer Olympic sports", 13],
["Name 4 sounds you can make when you mean Yuck", 9],
["Name 4 types of fish and 3 human bones", 15],
["Name 4 things you can't buy at Walmart", 14],
["Name 5 US cities that don't have a pro sports team", 11],
["Name 5 places you've never been", 9],
["Name 3 things that are hot and 4 breeds of dogs", 14],
["Name 3 flavors of jelly and 4 types of beans", 15],
["Name 5 types of cards", 14],
["Name 6 words you hear in math class", 13],
["Name 4 types of bugs and 2 things you can spray", 13],
["Name 3 things you drink from a cup and 3 types of cakes", 12],
["Using a monotone voice, name 5 things you find in a classroom", 12],
["While yawning, name 5 things you do right after waking up", 12],
["Name 5 things that start with Super", 12],
["Name 5 places you don't want to be right now", 11],



];
