
const Rather = [
["marry an enthusiastic cockroach farmer"],
["eat a large bowl of gummy worm spaghetti"],
["join a thrash metal band"],
["use the professional email address CrazyCatLady@gmail.com for your business"],
["have glow in the dark toenails"],
["write your own obituary"],
["host bingo in a retirement home"],
["let a 6 year old choose your outfit for a job interview"],
["sneeze 33 times in a row every morning"],
["be elected treasurer of a knitting club"],
["join an improv troupe"],
["take your next vacation in Fort Wayne, Indiana"],
["always wear toe socks"],
["read the Complete and Unabridged History of Soap Making"],
["live in a Las Vegas casino"],
["carry a mouse around in your pocket"],
["write an essay on the physics of boomerang throwing"],
["go to work in Snoopy pajamas"],
["go by the nickname &quot;Marbles&quot;"],
["visit the Museum of Nail Clippers"],
["be interviewed for Doofus Magazine"],
["have a video of you singing in the shower go viral"],
["compete in a high-stakes hopscotch tournament"],
["have your phone ding every time someone wins a prize on <i>The Price is Right</i>"],
["spend your birthday writing spoken word poetry in Panera"],
["have a disease named after you"],
["go on a retreat for competitive solitaire players"],
["have an old-timey car horn that goes <i>ah-oooooga</i>"],
["wear a shirt with a picture of your face on it"],
["wear bright red contact lenses"],
["stay at the Clown Motel"],
["attend a cocktail party wearing a kilt"],
["go through a car wash in a convertible"],
["post your coloring book artwork on Facebook"],
["teach driver's education"],
["have the personalized license plate DUMHEAD"],
["go on tour with a barbershop quartet"],
["name your dog <i>Kidney Stone</i>"],
["decorate lavishly for Flag Day"],
["record a podcast about metal detecting"],
["eat a bowl of five-alarm chili"],
["broadcast your dreams live on YouTube"],
["bet $500 on a snail race"],
["chaperone a high school prom"],
["be an umbrella hat model"],
["speak and write using old British English"],
["work in a year-round Christmas store"],
["go to bat against a wild pitcher throwing a 100-mph fastball"],
["get a tattoo depicting your favorite song from high school"],
["participate in a 24-hour dance-a-thon"],
["spend the night in a graveyard"],
["work as a poetry busker at a renaissance faire"],
["live in Amarillo, Texas"],
["honk like a goose every time you meet someone new"],
["capture a skunk"],
["skinny-dip on a busy night at the Bellagio fountain"],
["transcribe the Constitution into pig latin"],
["perform an edgy stand-up comedy set about having athlete's foot"],
["deejay a weekly radio show of experimental acid jazz"],
["lose $.25 every time you use the letter V"],
["ask if they have sarsaparilla every time someone takes your order"],
["drink only by using a crazy straw"],
["decorate your lawn with a flock of plastic flamingos"],
["sit next to a talkative ventriloquist on a 10-hour flight"],
["dig holes"],
["wear size 14 shoes"],
["take a selfie at a funeral"],
["go camping in the Everglades"],
["have your face on a billboard ad for anti-lice shampoo"],
["work in a New Orleans voodoo shop"],
["use soap that smells like ranch dressing"],
["make small talk with strangers on an elevator"],
["make your browser history public"],
["blow soap bubbles from your nose every time you wash your hands"],
["sort 10,000 ping-pong balls"],
["live in a glamping yurt"],
["have a phone that plays showtunes while charging"],
["attend a speed-dating event in a skimpy bathing suit"],
["give motivational speeches"],
["walk the red carpet wearing a chicken suit"],
["chew pork chop flavored gum"],
["drive across Rhode Island on a riding lawn mower"],
["work as a snake handler"],
["write only using a feather quill"],
["send exactly three text messages every day"],
["speak with a thick Boston accent"],
["wear burlap underwear"],
["slap Santa Claus"],
["every time you buy something, tell the cashier a knock knock joke"],
["join a debate team and argue that taxes should be higher"],
["run across a snow covered football field barefoot"],
["brush your teeth with mayonnaise"],
["climb the stairs to the top of the Empire State Building"],
["work as an outdoor window washer for a skyscraper"],
["stay at a hippie commune"],
["be the subject of a famous rapper's scathing diss track"],
["get into a tickle fight with your neighbor"],
["attend an outdoor movie festival in a pouring rain storm"],
["ride a merry-go-round for 6 hours"],
["see the Mothman (not the movie, the actual Mothman)"],
["go slam dancing"],
["have your day-to-day life filmed for a reality TV show"],
["use a phone that never charges past 30%"],
["have a password protected toilet in your bathroom"],
["ask 30 strangers to take a selfie with you"],
["have a ringtone that loudly announces who is calling you"],
["have 12 mannequins on display in your house"],
["drink a glass of orange juice each night after brushing your teeth"],
["wear sunglasses on the back of your head at all times"],
["write a thank you note every time you order a meal"],
["have a small butterfly follow you everywhere you go"],
["work the phrase <i>Spoiler alert!</i> into conversation twice a day"],
["have a mild emoji allergy"],
["sleep in a coffin"],
["drink 5 Red Bulls a day for a 2 weeks"],
["give a sermon speaking grammatically like Yoda"],
["live an Amish lifestyle for 2 months"],



];

