

CompareCategory  = [
["sports mascot"],
["vegetable"],
["type of sandwich"],
["punctuation mark"],
["kitchen utensil"],
["coin denomination"],
["mythical creature"],
["farm animal"],
["type of cheese"],
["type of pasta"],
["type of bean"],
["body part"],
["household appliance"],
["animal at the aquarium"],
["type of hat"],
["Mexican food"],
["item at a convenience store"],
["ice cream flavor"],
["part of a car"],
["vegetarian food"],
["piece of winter clothing"],
["holiday decoration"],
["thing from Australia"],
["electric gadget"],
["item in a toolbox"],
["type of fastener"],
["cleaning item"],
["odorous item"],
["Halloween costume"],
["ointment or lotion"],
["drug store purchase"],
["piece of stationery"],
["famous artwork"],
["bakery food"],
["musical instrument"],
["body organ"],
["item in a beach bag"],
["exercise equipment"],
["flying insect"],
["poisonous thing"],
["item used by a plumber"],
["rodent"],
["salad dressing"],
["type of shoe"],
["piece of linen"],
["item in a souvenir shop"],
["classroom item"],
["piece of camping equipment"],
["playing card"],
["type of balloon animal"],
["item in a vending machine"],
["item in a junk drawer"],
["magician's prop"],
["unhealthy food"],
["farmer's market purchase"],
["item in the circus"],
["item in your medicine cabinet"],
["item in a doctor's office"],
["children's toy"],
["piece of jewelry"],
["zoo animal"],
["safari animal"],
["plant or flower"],
["type of pants"],
["type of office supplies"],
["item in a gym bag"],
["fast food item"],
["item found in a pet supply store"],
["item from in a sci-fi movie"],
["item from Hawaii"],
["bathroom item"],
["collectible item"],
["item owned by a pirate"],
["item in your nightstand"],
["item in a hotel room"],
["item used by a gardener"],
["type of sports ball"],
["video game or board game"],
["type of art supply"],
["type of transportation"],
["road sign"],
["item used for personal hygiene"],
["item with a zipper"],
["item that can fit in your pocket"],
["item found on a farm"],
["item in a science lab"],
["item found at a pool party"],
["book"],
["popular item from the 1900s"],
["piece of formal attire"],
["item currenly in your refrigerator"],
["item from a hardware store"],
["item in a first aid kit"],
["item associated with Christmas"],
["thing that gets hot"],
["cartoon character"],
["type of seat"],
["item sold in a stadium"],
["fragile item"],
["item in your glove compartment or trunk"],

];










CompareAdjective  = [
["is the most life threatening"],
["is annoyingly pretentious"],
["is the most dignified"],
["is the most old fashioned"],
["is the most puzzling"],
["is the most versatile"],
["is the most fun to smell"],
["is the most effervescent"],
["is the most heartwarming"],
["is the most adequate"],
["is the most comfortable to sit on"],
["is surprisingly beautiful"],
["is the most life-changing"],
["is the most stress-inducing"],
["would be most fun to destroy"],
["is the most aesthetically pleasing"],
["would be most fun to show to an alien"],
["is the most stunning"],
["is the most fun at midnight"],
["would make the best good luck charm"],
["would be coolest on a tee shirt"],
["would be most pleasing to a grandmother"],
["is the most soulful"],
["would be most confusing to a time traveler"],
["is the most unpleasant when damp"],
["is the most ergonomically flawless"],
["is the spookiest"],
["is the most uncomfortable when sticky"],
["is the most soothing"],
["is the most hypnotic"],
["is completely useless"],
["would be most disgusting to lick"],
["would survive the apocalypse"],
["would you want as a tattoo"],
["would make a good hat"],
["is the most suspicious"],
["is best to bring on vacation"],
["would be best at a birthday party"],
["attracts the most bees"],
["would influencers do a viral video about"],
["would mean trouble if used by a supervillain"],
["has the best stories to tell"],
["would you bring on a romantic Valentines Day date"],
["makes everyone the most uncomfortable"],
["would you hate to see in your neighbor's yard"],
["would be worst when frozen"],
["leaves the worst stain"],
["would you never buy used"],
["should come with a warning label"],
["would instantly improve your day"],
["would you give to an astronaut before takeoff"],
["would be useful in a secret espionage plot"],
["would you want on a deserted island"],
["would you like to see a documentary about"],
["can instantly ruin your day"],
["deserves more respect"],
["is definitely a rich person's thing"],
["would be worst to clean with a toothbrush"],
["would you be embarrassed be seen with"],
["will be in your nightmares forever"],
["would help a detective solve a murder case"],
["would your teenage self have hated"],
["would you never buy at a haunted voodoo shop"],
["would be most surprising to get in the mail"],
["would make a terrible retirement gift"],
["would you like to hear a country song about"],
["should be on a flag"],
["would you not want to bring through airport security"],
["would make the best fish bait"],
["would make the best splash"],
["could make you cry"],
["would you bring in for show and tell"],
["would your doctor prescribe for you"],
["could start an international scandal"],
["would you be most surprised to find while snorkeling"],
["would you want on a long, boring drive"],
["would you give to your significant other on their birthday"],
["would a tough guy carry around"],
["would you not want to spell in a spelling bee"],
["would you like to dream about tonight"],
["would make the best exclamation when you yell '<i>Holy ___!</i>'"],
["would make the best rapper's name"],
["would you be most surprised to find on Etsy"],
["would cheer you up in a hospital"],
["would you like to hear spoken in a French accent"],
["would you like to see an artistic painting of"],
["could a comedian do a funny bit about"],
["can we all agree is awesome"],
["would make a good name for a heavy metal band"],
["is the most underrated"],
["would you choose as your middle name"],
["would make a good weapon for a murder mystery"],
["are you most likely to buy online at 2AM"],
["would you leave to your grandkids in your will"],
["would you want to get autographed by a famous person"],
["would be a controversial topic at Thanksgiving dinner"],
["would make the biggest mess if it exploded"],
["would you give to your dog to chew on"],
["would make an incredibly boring podcast topic"],
["should be banished from existence"],
["has no soul"],

];


















