const scenes = [
  "Bad things to hear from your GPS",
  "What not to say on a first date",
  "Unlikely things to hear from your dentist",
  "Bad times to get the hiccups",
  "Health advice from a bad doctor",
  "Awkward things to say in an elevator",
  "Annoying requests for your flight attendant",
  "Bad things to hear while going into surgery",
  "Things that should not be a subscription service",
  "Lines that shouldn't be in your wedding vows",
  "Bad ideas for scented candle",
  "Events that shouldn't be live-streamed",
  "Things you shouldn't say in a job interview",
  "Things your should never tell your boss",
  "Bad team-building exercises",
  "Uninspiring office perks",
  "Awkward ways to end a Zoom call",
  "Weird alerts to get on your phone",
  "Things you shouldn't Google at work",
  "Bad advice from tech support",
  "Bad places to break up with your partner",
  "Bad places for a romantic dinner",
  "Worst things to overshare on a first date",
  "Bad questions to ask on a first date",
  "Places you shouldn't go with your dog",
  "What your cat is thinking at 3am",
  "If animals had human jobs",
  "Bad things to hear your parrot say",
  "What zoo animals do after closing time",
  "New laws if dogs ran the country",
  "Bad things to hear your waiter say",
  "Bad things to hear your chef say",
  "Bad things to hear your hairdresser say",
  "Weird orders at Chipotle",
  "Weird requests for your barista",
  "Announcements you don't want to hear from your pilot",
  "Worst person to sit next to on a plane",
  "Bad honeymoon destinations",
  "Embarrassing problems of the ultra rich",
  "Weird high school classes",
  "Weird college majors",
  "Boring reality TV shows",
  "If restaurant advertising was truthful",
  "Weird YouTube channels",
  "Inappropriate times to take a selfie",
  "If politicians made truthful commercials",
  "Rejected state mottos",
  "Weird occasions for a greeting card",
  "Unlikely game shows",
  "Odd things to read in a message from a bottle",
  "Unlikely things to read in a school textbook",
  "Things you shouldn't say to a traffic cop",
  "Bad excuses for being late to work",
  "Bad advice from your therapist",
  "Odd places to hold a kid's birthday party",
  "Weird naming rights for a stadium",
  "Things you shouldn't say to the IRS",
  "Bad 911 operators",
  "Inappropriate comments from a priest at a wedding",
  "Boring nature documentaries",
  "If graduation speeches were realistic",
  "Things not to say at the gym",
  "Bad motivational speeches",
  "Weird food vendors at a baseball game",
  "Unsettling things to hear from the FedEx driver",
  "Very mild insults",
  "When April Fools jokes go too far",
  "Things you don't want to hear from a fortune teller",
  "Unlikely experiments in high school science class",
  "When superhero rescues go wrong",
  "Things that shouldn't have alarms",
  "Bad people to share a life raft with",
  "Things you'd never hear at a celebrity telethon",
  "Strange lines to hear in a sci-fi movie",
  "Bad birthday gifts",
  "Weird things for boy scouts to sell as a fundraiser",
  "Inappropriate magic tricks",
  "Strange things to see on a children's TV show",
  "Names of cars that would never sell",
  "Bad shampoo ads",
  "Practical jokes in the animal kingdom",
  "If dogs could talk",
  "Unlikely events at the Olympics",
  "Presidential slogans that will not get you elected",
  "Baseball umpires when they're not at the ballpark",
  "Other things said by the person to walk on the moon",
  "Rejected Jeopardy categories",
  "What the grim reaper does to relax",
  "Least checked out library books",
  "Bad show and tell items",
  "Things you shouldn't buy used at a yard sale",
  "Things you'll never hear in a boxing ring",
  "Bad choices for pets",
  "Dangerous things to do in a swimsuit",
  "Odd kidnapper demands",
  "Things you'll regret saying to your cellmates",
  "Unwelcome dishes at a church potluck dinner",
  "Worst thing to find in your parachute pack",
  "Alternate endings to famous films",
  "What doctors see when they look in your ear",
  "Bad things to say to someone on their deathbed",
  "Prizes you'd like to find in your cereal box",
  "Lines you shouldn't open a sermon with",
  "What penguins are really thinking",
  "Strange causes to raise money for",
  "Hobbies of the stupid",
  "America's least popular monuments",
  "Modern additions to the Ten Commandments",
  "If dogs told jokes",
  "Inappropriate times to break into laughter",
  "Bad things to do during an earthquake",
  "People you wish would just shut up",
  "Things you shouldn't do when confronted by street gang",
  "Difficult things to sell door to door",
  "Celebrating everyday events as if you scored a touchdown",
  "Unusual uses for your cat",
  "Things to say that will always start a fight",
  "The shortest book ever written",
  "What they really talk about in football huddles",
  "Newspaper headlines you'd really like to see",
  "The wrong thing to say to a heartbroken friend",
  "Inlaws that make you rethink your engagement",
  "Self-help titles that didn't sell well",
  "Things you shouldn't say while winking",
  "Rejected sayings on candy heart valentines",
  "Trying to look cool while doing very uncool things",
  "Odd things to see on highway warning signs",
  "If you could fast forward in real life",
  "Improper etiquette when meeting the queen",
  "The good news... and the bad news",
  "Conversation topics that will derail a dinner party",
  "Original rejected poses for the Mona Lisa",
  "Odd choices for a presidential running mate",
  "Times you'd like to say 'Let's see that again in slow motion'",
  "Bad names for perfume",
  "Unusual cases for the FBI",
  "What your dog does when you leave him alone",
  "Terrible catchphrases",
  "If people broke into song in real life",
  "What Olympic medalists are really thinking on the podium",
  "The first words really spoken over the telephone",
  "What the pilot shouldn't have said while the intercom was on",
  "First lines of the worst poems ever written",
  "Things that shouldn't have ejector seats",
  "Bad things to do as you walk down the aisle at your wedding",
  "What you don't want to see tattooed on your date",
  "Weird things for people to find beautiful",
  "Weird things for your grandmother to give you for Christmas",
  "Boy scout badges we've never heard of",
  "Unsuccessful diet books",
  "Bad racehorse names to bet on",
  "Times it would be nice to be beamed up",
  "Superman's secret inner thoughts",
  "Bad racehorse names to bet on",
  "Things you do as a child that aren't as cute as an adult",
  "If celebrities had been the first person to walk on the moon",
  "If actors were completely honest during award accpetance speeches",
  "Circus acts that didn't last long",
  "Odd things for a lounge singer to sing about",
  "If you could give children just one piece of advice, it would be...",
  "Unlikely souvenir tee shirts",
  "If human doctors acted like animal doctors",
  "Difficult things to say with a straight face",
  "Announcements made over hell's PA system",
  "Versions of hell other than eternal flames",
  "If morning show hosts acted like most people in the morning",
  "Announcements that tend to ruin a party",
  "Unusual things for your neighbor to ask to borrow",


];




