const scenes = [
  "Bad things to hear from your GPS",
  "What not to say on a first date",
  "Unlikely things to hear from your dentist",
  "Bad times to get the hiccups",
  "Health advice from a bad doctor",
  "Awkward things to say in an elevator",
  "Annoying requests for your flight attendant",
  "Bad things to hear while going into surgery",
  "Things that should not be a subscription service",
  "Lines that shouldn't be in your wedding vows",
  "Bad ideas for scented candle",
  "Events that shouldn't be live-streamed",
  "Things you shouldn't say in a job interview",
  "Things your should never tell your boss",
  "Bad team-building exercises",
  "Uninspiring office perks",
  "Awkward ways to end a Zoom call",
  "Weird alerts to get on your phone",
  "Things you shouldn't Google at work",
  "Bad advice from tech support",
  "Bad places to break up with your partner",
  "Bad places for a romantic dinner",
  "Worst things to overshare on a first date",
  "Bad questions to ask on a first date",
  "Places you shouldn't go with your dog",
  "What your cat is thinking at 3am",
  "If animals had human jobs",
  "Bad things to hear your parrot say",
  "What zoo animals do after closing time",
  "New laws if dogs ran the country",
  "Bad things to hear your waiter say",
  "Bad things to hear your chef say",
  "Bad things to hear your hairdresser say",
  "Weird orders at Chipotle",
  "Weird requests for your barista",
  "Announcements you don't want to hear from your pilot",
  "Worst person to sit next to on a plane",
  "Bad honeymoon destinations",
  "Embarrassing problems of the ultra rich",
  "Weird high school classes",
  "Weird college majors",
  "Boring reality TV shows",
  "If restaurant advertising was truthful",
  "Weird YouTube channels",
  "Inappropriate times to take a selfie",
  "If politicians made truthful commercials",
  "Rejected state mottos",
  "Weird occasions for a greeting card",
  "Unlikely game shows",
  "Odd things to read in a message from a bottle",
  "Unlikely things to read in a school textbook",
  "Things you shouldn't say to a traffic cop",
  "Bad excuses for being late to work",
  "Bad advice from your therapist",
  "Odd places to hold a kid's birthday party",
  "Weird naming rights for a stadium",
  "Things you shouldn't say to the IRS",
  "Bad 911 operators",
  "Inappropriate comments from a priest at a wedding",
  "Boring nature documentaries",
  "If graduation speeches were realistic",
  "Things not to say at the gym",
  "Bad motivational speeches",
  "Weird food vendors at a baseball game",
  "Unsettling things to hear from the FedEx driver",
  "Very mild insults",
  "When April Fools jokes go too far",
  "Things you don't want to hear from a fortune teller",
  "Unlikely experiments in high school science class",
  "When superhero rescues go wrong",
  "Things that shouldn't have alarms",
  "Bad people to share a life raft with",
  "Things you'd never hear at a celebrity telethon",
  "Strange lines to hear in a sci-fi movie",
  "Bad birthday gifts",
  "Weird things for boy scouts to sell as a fundraiser",
  "Inappropriate magic tricks",
  "Strange things to see on a children's TV show",
  "Names of cars that would never sell",
  "Bad shampoo ads",
  "Practical jokes in the animal kingdom",
  "If dogs could talk",
  "Unlikely events at the Olympics",
  "Presidential slogans that will not get you elected",
  "Baseball umpires when they're not at the ballpark",
  "Other things the first man on the moon said",
  "Rejected Jeopardy categories",
  "What the grim reaper does to relax",
  "Least checked out library books",
  "Bad show and tell items",
  "Things you shouldn't find used at a yard sale",
  "Things you'll never hear in a boxing ring",
  "Bad choices for pets",
  "Dangerous things to do in a swimsuit",
  "Odd kidnapper demands",
  "Things you'll regret saying to your cellmates",
  "Unwelcome dishes at a church potluck dinner",
  "Worst thing to find in your parachute pack",
  "Alternate endings to famous films",
  "What doctors see when they look in your ear",
  "Bad things to say to someone on their deathbed",
  "Prizes you'd like to find in your cereal box",
  "Lines you shouldn't open a sermon with",
  "What penguins are really thinking",
  "Strange causes to raise money for",
  "Hobbies of the stupid",
  "America's least popular monuments",
  "Modern additions to the Ten Commandments",
  "If dogs told jokes",
  "Inappropriate times to break into laughter",
  "Bad things to do during an earthquake",


];




