const scenes = [
  "Bad things to hear from your GPS",
  "What not to say on a first date",
  "Things you don't want to hear from your dentist",
  "Bad times to get the hiccups",
  "Health advice from a bad doctor",
  "Awkward things to say in an elevator",
  "Annoying requests for your flight attendant",
  "Bad things to hear while going into surgery",
  "Things that should not be a subscription service",
  "Lines that shouldn't be in your wedding vows",
  "Bad ideas for scented candle",
  "Events that shouldn't be live-streamed",
  "Things you shouldn't say in a job interview",
  "Things your should never tell your boss",
  "Bad team-building exercises",
  "Uninspiring office perks",
  "Awkward ways to end a Zoom call",
  "Weird alerts to get on your phone",
  "Things you shouldn't Google at work",
  "Bad advice from tech support",
  "Bad places to break up with your partner",
  "Bad places for a romantic dinner",
  "Worst things to overshare on a first date",
  "Bad questions to ask on a first date",
  "Places you shouldn't go with your dog",
  "What your cat is thinking at 3am",
  "If animals had human jobs",
  "Bad things to hear your parrot say",
  "What zoo animals do after closing time",
  "New laws if dogs ran the country",
  "Bad things to hear your waiter say",
  "Bad things to hear your chef say",
  "Bad things to hear your hairdresser say",
  "Weird orders at Chipotle",
  "Weird requests for your barista",
  "Announcements you don't want to hear from your pilot",
  "Worst people to sit next to on a plane",
  "Bad honeymoon destinations",
  "Embarrassing problems of the ultra rich",
  "Weird high school classes",
  "Weird college majors",
  "Boring reality TV shows",
  "If restaurant advertising was truthful",
  "Weird YouTube channels",
  "Inappropriate times to take a selfie",
  "If politicians made truthful commercials",
  "Rejected state mottos",
  "Weird occasions for a greeting card",
  "Unlikely game shows",
  "Odd things to read in a message from a bottle",
  "Unlikely things to read in a school textbook",
  "Things you shouldn't say to a traffic cop",
  "Bad excuses for being late to work",
  "Bad advice from your therapist",
  "Odd places to hold a kid's birthday party",
  "Weird naming rights for a stadium",
  "Things you shouldn't say to the IRS",
  "World's worst 911 operator",
  "Inappropriate comments from a priest at a wedding",
  "Boring nature documentaries",
  "If graduation speeches were realistic",
  "Things not to say at the gym",
  "Bad motivational speeches",
  "Weird food vendors at a baseball game",
  "Unsettling things to hear from the FedEx driver",
  "Very mild insults",
  "When April Fools jokes go too far",
  "Things you don't want to hear from a fortune teller",



];


